// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: jvjexxlnztfaurzsixvn

class SupabaseConfig {
  static const String supabaseUrl = 'https://jvjexxlnztfaurzsixvn.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2amV4eGxuenRmYXVyenNpeHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTE0ODQsImV4cCI6MjA3NTMyNzQ4NH0.cbbX89u74yvZcF_ZxEYNfznsKVsIm1JYg9eNJA9uxHI';
}
